name: Release

on:
  schedule:
    # every Sunday at 12:00 UTC (00:00 AOE)
    - cron: "0 12 * * 0"
  workflow_dispatch:
    inputs:
      nightly:
        required: false
        type: boolean
        default: "true"
      release_name:
        required: false
        type: string
      release_tag:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PACKAGE_ID: "moly-local"

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    needs: [build]
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Determine release tag
        if: ${{ ! github.event.inputs.release_tag }}
        run: |
          export TZ=UTC
          version=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[] | select(.name == "${{ env.PACKAGE_ID }}") | .version')

          if [[ "${{ github.event.inputs.nightly }}" == "true" ]]; then
              echo "RELEASE_TAG=v${version}+nightly.$(date +'%Y%m%d')" >> "$GITHUB_ENV"
          else
              echo "RELEASE_TAG=v${version}" >> "$GITHUB_ENV"
          fi

      - name: Determine release name
        if: ${{ ! github.events.inputs.release_name }}
        run: |
          echo "RELEASE_NAME=${{ env.PACKAGE_ID }} ${{ env.RELEASE_TAG }}" >> "$GITHUB_ENV"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GH_PAT }}

      - name: Generate archives
        run: |
          for dir in moly-local-*; do
              if [[ $dir == *"windows"* ]]; then
                  echo "Generating ZIP archive: ${dir}.zip"
                  zip -r "${dir}.zip" "$dir"
              else
                  echo "Generating tarball: ${dir}.tar.gz"
                  tar -czf "${dir}.tar.gz" "$dir"
              fi
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.RELEASE_TAG }}
          prerelease: ${{ github.events.inputs.nightly == 'true' }}
          files: |
            moly-local-*.tar.gz
            moly-local-*.zip
          body: |
            Build version: `${{ env.RELEASE_TAG }}` (${{ github.sha }})
          token: ${{ secrets.GH_PAT }}
